### ISSUE TITLE
Unable to mount layout to NodeCG.

### ISSUE THREAD

**Issue by DawsonHarvey** [GamesDoneQuick/agdq18-layouts#6]
After following all the installation instructions for setting up NodeCG and installing this bundle, I am seemingly unable to use it due to errors with the configuration. I am attempting to properly setup the JSON file in accordance to how it is organized in the schema, but I cannot seem to get past certain errors, specifically the "osc" module not being found. A clearer guide on the configuration would be helpful.

**Comment by Lange** [comment]
Can you copy/paste or screenshot the exact error you're having? From your description, it sounds like it might be a dependency issue, and not a configuration issue,

**Comment by DawsonHarvey** [comment]
Here is a screenshot of the error with the osc module. The reason I feel this is a configuration issue is because I don't intend on using this module in the first place, since I don't have the associated hardware it describes (Behringer X32). There must surely be a way to run it without the module, yet how to do so is not clear to me.
![](http://puu.sh/z8H8u/434d6c3b3c.png)

**Comment by Lange** [comment]
That particular error does indeed mean that NodeCG is trying to load the `osc` dependency, but is unable to do so because it is not installed. When you ran `npm install`, you may have encountered some errors. These errors were likely due to not having a compiler toolchain installed. A compiler toolchain is necessary to install certain dependencies, because they are "native" dependencies, and not all native dependencies ship with pre-built binaries. In these instances, they have to be compiled at install time.

If you re-run `npm install`, you'll likely see these errors. Resolving them would mean installing a compiler toolchain via the instructions in the [README](https://github.com/GamesDoneQuick/agdq18-layouts/blob/master/README.md#installation).

> There must surely be a way to run it without the module, yet how to do so is not clear to me.

This isn't always the case. Bear in mind that this project is developed for a single use case, and open-sourced as a courtesy. It won't be as user-friendly as many other open source projects, because it's only built to function in the exact way we need it to at GDQ. We did not build it to support a wide array of use cases; we built it to support exactly one use case. People who wish to operate outside of that one very narrow use case may encounter friction.

As of right now, there's no way to avoid loading the `osc` library, because it's used in two places:

1. [extension/mixer.js#L10](https://github.com/GamesDoneQuick/agdq18-layouts/blob/master/extension/mixer.js#L10)
2. [extension/caspar.js#L10](https://github.com/GamesDoneQuick/agdq18-layouts/blob/master/extension/caspar.js#L10)

The instance in `extension/caspar.js` is currently always loaded, regardless of configuration. If you want to run `agdq18-layouts` without installing the `osc` dependency, you'll have to fork this repo and modify it to not execute `extension/caspar.js`.

**Comment by DawsonHarvey** [comment]
I did install the compiler toolchain as explained, but I think I did so later than I should have, which is my mistake.

In any case, after fixing that I will do as you say and attempt to fork the code for my own purposes. I was just hoping that wouldn't be necessary to just run it for the first time. 
Thank you for your time and patience.
